"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { getClientSessionSnapshot } from "@/lib/clientAuth";
import { fetchAccountStatus } from "@/lib/accountStatusClient";
import { Image20SidebarShell } from "@/components/image20/Image20Chrome";

type Room={id:string;title:string;duration_minutes:number;mode:"group"|"pair";max_size:number;created_at:string;created_by:string;daily_room_url?:string|null;visibility?:"public"|"members"|"friends"|"invited"|null;invite_code?:string|null};
type Bootstrap={room:Room;is_owner:boolean;is_member:boolean;can_join:boolean;requires_invite_code:boolean;invite_code_accepted:boolean};
type Token={token:string;exp:number;duration_minutes:number;cost_credits:number;free_monthly_allowance:number;remaining_credits:number|null;is_vip:boolean;allowed_by_pair_vip_carry:boolean};

export default function RoomDetailPage(){
  const router=useRouter(); const params=useParams<{roomId:string}>(); const search=useSearchParams(); const roomId=params?.roomId; const inviteFromUrl=(search.get('invite')||search.get('code')||'').trim().toUpperCase();
  const [email,setEmail]=useState(''); const [accessToken,setAccessToken]=useState(''); const [room,setRoom]=useState<Room|null>(null); const [isMember,setIsMember]=useState(false); const [canJoin,setCanJoin]=useState(false); const [dailyToken,setDailyToken]=useState(''); const [tokenInfo,setTokenInfo]=useState<Token|null>(null); const [inviteCode,setInviteCode]=useState(inviteFromUrl); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false); const [presence,setPresence]=useState<'quiet'|'audio'|'mosaic'|'camera'>('quiet'); const [brb,setBrb]=useState(false); const [aiOpen,setAiOpen]=useState(false);
  useEffect(()=>{let c=false;(async()=>{const session=await getClientSessionSnapshot().catch(()=>null);if(!session){router.replace('/auth/login');return;}if(c)return;setEmail(session.email);setAccessToken(session.accessToken??'');await bootstrap(session.accessToken??'',inviteFromUrl);})();return()=>{c=true}},[router,roomId]);
  const callUrl=useMemo(()=>{if(!room?.daily_room_url||!dailyToken)return '';const sep=room.daily_room_url.includes('?')?'&':'?';return `${room.daily_room_url}${sep}t=${encodeURIComponent(dailyToken)}`},[room?.daily_room_url,dailyToken]);
  async function bootstrap(token=accessToken, invite=inviteCode){if(!roomId)return;setBusy(true);setMsg('');try{const res=await fetch('/api/rooms/bootstrap',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({roomId,inviteCode:invite||undefined})});const json=await res.json().catch(()=>({}));if(!res.ok)throw new Error(json?.error||'讀取房間資訊失敗。');const data=json as Bootstrap;setRoom(data.room);setIsMember(Boolean(data.is_member||data.is_owner));setCanJoin(Boolean(data.can_join||data.is_member||data.is_owner));if(data.is_member||data.is_owner) await requestToken(token);}catch(e:any){setMsg(e?.message||'讀取房間失敗。')}finally{setBusy(false)}}
  async function join(){if(!roomId)return;setBusy(true);setMsg('');try{const res=await fetch('/api/rooms/join',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`},body:JSON.stringify(inviteCode?{inviteCode}:{roomId})});const json=await res.json().catch(()=>({}));if(!res.ok)throw new Error(json?.error||'加入失敗');setIsMember(true);setCanJoin(true);await requestToken(accessToken);}catch(e:any){setMsg(e?.message||'加入房間失敗。')}finally{setBusy(false)}}
  async function requestToken(token=accessToken){if(!roomId)return;setBusy(true);try{const res=await fetch('/api/daily/meeting-token',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({roomId})});const json=await res.json().catch(()=>({}));if(!res.ok)throw new Error(json?.error||'取得 meeting token 失敗。');setDailyToken(json.token);setTokenInfo(json as Token);await fetchAccountStatus(token).catch(()=>null);}catch(e:any){setMsg(e?.message||'取得視訊權限失敗。')}finally{setBusy(false)}}
  return <Image20SidebarShell title="房內空間" email={email}><div className="i20-call-shell" data-image20-dom-page="room-detail-v6"><section className="i20-call-stage"><div className="i20-call-bg"/><div style={{position:'absolute',zIndex:2,left:26,top:24,color:'#fff'}}><span className="i20-kicker">In-room</span><h2 className="i20-serif" style={{fontSize:36,margin:'8px 0'}}>{room?.title||'同行房間'}</h2><div className="i20-chip-row"><span className="i20-chip active">{room?.duration_minutes??25} 分鐘</span><span className="i20-chip active">{room?.mode==='pair'?'雙人':'小組'}</span><span className="i20-chip active">Presence: {presence}</span></div></div>{callUrl?<iframe src={callUrl} allow="camera; microphone; fullscreen; speaker; display-capture" style={{position:'absolute',inset:0,width:'100%',height:'100%',border:0,zIndex:1}} title="Daily room"/>:<div className="i20-video-grid"><div className="i20-video-tile">等待取得視訊權限</div><div className="i20-video-tile">加入後會顯示其他參與者</div></div>}<div className="i20-call-controls" style={{zIndex:4}}><button onClick={()=>setPresence('quiet')}>靜</button><button onClick={()=>setPresence('audio')}>聲</button><button onClick={()=>setPresence('mosaic')}>柔</button><button onClick={()=>setPresence('camera')}>鏡</button><button onClick={()=>setBrb(v=>!v)}>{brb?'回':'BRB'}</button><button onClick={()=>setAiOpen(v=>!v)}>AI</button><button className="leave" onClick={()=>router.push('/rooms')}>離</button></div></section><aside className="i20-call-side"><section className="i20-panel dark"><span className="i20-kicker">Room State</span><h3>安全進房流程</h3>{msg?<p style={{color:'#ffc6b9'}}>{msg}</p>:null}<div className="i20-list"><div className="i20-softbar"><b>成員</b><span>{isMember?'已加入':'尚未加入'}</span></div><div className="i20-softbar"><b>Token</b><span>{dailyToken?'已簽發':'未簽發'}</span></div><div className="i20-softbar"><b>扣場</b><span>{tokenInfo?.cost_credits??'?'} credits</span></div></div>{!isMember?<><div className="i20-field" style={{marginTop:12}}><label>邀請碼</label><input className="i20-input" value={inviteCode} onChange={e=>setInviteCode(e.target.value.toUpperCase())}/></div><button className="i20-btn peach" onClick={join} disabled={busy||!canJoin&&!inviteCode}>加入房間</button></>:<button className="i20-btn" onClick={()=>requestToken(accessToken)} disabled={busy}>續下一場 / 重新取 token</button>} {room?.visibility==='invited'&&room.invite_code?<p>邀請碼：{room.invite_code}</p>:null}</section><section className="i20-panel"><span className="i20-kicker">Presence</span><h3>不強迫開鏡頭</h3><p>本版先以前端 UI 保留 quiet / audio / mosaic / camera 與 BRB 狀態；若要持久化，請套用 SQL 內的 presence events。</p></section>{aiOpen?<section className="i20-panel dark"><span className="i20-kicker">Room AI</span><h3>Shared Host AI</h3><p>可用於開場、轉場與收尾。未串接 server gate 前不會送出對話或消耗 AI 額度。</p><button className="i20-btn ghost">開始救援（預留）</button></section>:null}<Link href="/rooms" className="i20-btn light">回房間列表</Link></aside></div></Image20SidebarShell>
}
