"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { FormalOpsShell, adminOpsNav } from "@/components/formalOps/FormalOpsShell";
import { formatDateTime, useAuthedJson } from "@/components/formalOps/useAuthedJson";
import styles from "@/components/image20/Image20Auxiliary.module.css";

type Issue = { id?: string; issue_type: string; severity: string; status?: string; room_id?: string | null; daily_room_name?: string | null; daily_room_url?: string | null; title: string; description?: string | null; recommended_action?: string | null; created_at?: string | null };
function severityWeight(value: string) { if (value === "critical") return 5; if (value === "urgent") return 4; if (value === "high") return 3; if (value === "normal") return 2; return 1; }

export default function AdminRoomReconciliationPage() {
  const { accessToken, authedFetch } = useAuthedJson("/admin/rooms/reconciliation");
  const [payload, setPayload] = useState<any>(null);
  const [message, setMessage] = useState("正在掃描房間與 Daily 狀態…");
  const [busyKey, setBusyKey] = useState("");
  async function load(persist = false) { const data = await authedFetch(`/api/admin/rooms/reconciliation${persist ? "?persist=1" : ""}`); setPayload(data); }
  useEffect(() => { if (!accessToken) return; load(false).then(() => setMessage("")).catch((error) => setMessage(error.message)); }, [accessToken]);
  const detected: Issue[] = useMemo(() => { const rows = payload?.issues || []; return [...rows].sort((a: Issue, b: Issue) => severityWeight(b.severity) - severityWeight(a.severity)); }, [payload]);
  const openItems: Issue[] = useMemo(() => payload?.open_items || [], [payload]);
  async function runScan() { setMessage("正在建立 reconciliation run…"); try { const data = await authedFetch("/api/admin/rooms/reconciliation", { method: "POST", body: JSON.stringify({ action: "scan", persist: true }) }); setPayload((prev: any) => ({ ...(prev || {}), ...data })); await load(false); setMessage("已建立 reconciliation run。"); } catch (error: any) { setMessage(error?.message || "掃描失敗。"); } }
  async function fixDetected(issue: Issue, action: "end_room" | "delete_daily_room" | "end_room_and_delete_daily") { const key = `${issue.issue_type}:${issue.room_id || issue.daily_room_name}:${action}`; setBusyKey(key); setMessage("正在執行修復動作…"); try { await authedFetch("/api/admin/rooms/reconciliation", { method: "POST", body: JSON.stringify({ action, room_id: issue.room_id, daily_room_name: issue.daily_room_name, reason: `admin_reconciliation_detected:${issue.issue_type}` }) }); await load(false); setMessage("已執行修復動作。"); } catch (error: any) { setMessage(error?.message || "修復失敗。"); } finally { setBusyKey(""); } }
  async function updateItem(item: Issue, action: string) { if (!item.id) return; setBusyKey(`${item.id}:${action}`); setMessage("正在更新 reconciliation item…"); try { await authedFetch(`/api/admin/rooms/reconciliation/items/${item.id}`, { method: "PATCH", body: JSON.stringify({ action }) }); await load(false); setMessage("已更新 reconciliation item。"); } catch (error: any) { setMessage(error?.message || "更新失敗。"); } finally { setBusyKey(""); } }
  return <FormalOpsShell activeHref="/admin/rooms/reconciliation" navItems={adminOpsNav} eyebrow="Daily Room Reconciliation" title="房間與 Daily 對帳" description="集中檢查 Supabase rooms、room_members、presence 與 Daily managed rooms，處理 ghost rooms、orphan Daily rooms 與逾期 active rooms。" quoteTitle={`${detected.length} detected / ${openItems.length} open`} quoteBody="正式平台不能讓使用者看得到房間、但後端或 Daily 狀態互相打架。" topActions={<><button type="button" onClick={runScan}>建立掃描紀錄</button><Link href="/admin/rooms">房間 360</Link><Link href="/admin/action-center">工作台</Link></>} dataPage="admin-room-reconciliation-v117">
    {message ? <div className={styles.accountLoading}>{message}</div> : null}
    {payload?.errors?.length ? <div className={styles.accountLoading}>讀取警告：{payload.errors.join("；")}</div> : null}
    <section className={styles.accountMetricGrid}><article className={styles.accountMetricCard}><span className="i20-kicker">Supabase</span><h3>Rooms scanned</h3><b>{payload?.scanned_supabase_rooms ?? "—"}</b><p>最近最多掃描 600 筆 rooms。</p></article><article className={styles.accountMetricCard}><span className="i20-kicker">Daily</span><h3>Managed rooms</h3><b>{payload?.scanned_daily_rooms ?? "—"}</b><p>{payload?.daily_error || "只看 cowork_ / buddy_ 管理房。"}</p></article><article className={styles.accountMetricCard}><span className="i20-kicker">Detected</span><h3>偵測問題</h3><b>{detected.length}</b><p>critical / urgent / high 需優先處理。</p></article><article className={styles.accountMetricCard}><span className="i20-kicker">History</span><h3>Open persisted items</h3><b>{openItems.length}</b><p>來自已保存的 reconciliation runs。</p></article></section>
    <section className={styles.accountContentGrid}><article className={styles.accountContentCard}><div className={styles.accountContentHead}><div><span className="i20-kicker">Live Scan</span><h3>即時偵測結果</h3></div><button type="button" onClick={() => load(false).catch((error) => setMessage(error.message))}>重新掃描</button></div><div className={styles.accountPreferenceList}>{detected.map((issue) => { const key = `${issue.issue_type}:${issue.room_id || issue.daily_room_name}`; return <div key={key}><b>{issue.severity}｜{issue.issue_type}</b><span>{issue.title}</span><span>{issue.description || "—"}</span><span>{issue.room_id ? <Link href={`/admin/rooms/${issue.room_id}`}>房間 360</Link> : null} {issue.room_id ? <button type="button" disabled={busyKey.includes(key)} onClick={() => fixDetected(issue, "end_room")}>結束 Supabase 房間</button> : null} {issue.daily_room_name ? <button type="button" disabled={busyKey.includes(key)} onClick={() => fixDetected(issue, "delete_daily_room")}>刪除 Daily room</button> : null} {issue.room_id && issue.daily_room_name ? <button type="button" disabled={busyKey.includes(key)} onClick={() => fixDetected(issue, "end_room_and_delete_daily")}>結束並刪 Daily</button> : null}</span></div>; })}{!detected.length ? <div><b>目前沒有偵測到房間 / Daily 不一致。</b><span>仍建議每天保留掃描紀錄。</span></div> : null}</div></article>
    <article className={styles.accountContentCard}><div className={styles.accountContentHead}><div><span className="i20-kicker">Open Items</span><h3>已保存待處理項目</h3></div></div><div className={styles.accountPreferenceList}>{openItems.map((item) => <div key={item.id}><b>{item.severity}｜{item.issue_type}｜{item.status}</b><span>{item.title}</span><span>{formatDateTime(item.created_at)}｜{item.recommended_action || "—"}</span><span>{item.room_id ? <Link href={`/admin/rooms/${item.room_id}`}>房間 360</Link> : null} <button type="button" onClick={() => updateItem(item, "mark_in_progress")}>處理中</button> <button type="button" onClick={() => updateItem(item, "mark_fixed")}>標記完成</button> <button type="button" onClick={() => updateItem(item, "ignore")}>忽略</button>{item.room_id ? <><br /><button type="button" onClick={() => updateItem(item, "end_room")}>結束房間</button></> : null}{item.daily_room_name ? <> <button type="button" onClick={() => updateItem(item, "delete_daily_room")}>刪 Daily</button></> : null}{item.room_id && item.daily_room_name ? <> <button type="button" onClick={() => updateItem(item, "end_room_and_delete_daily")}>結束並刪 Daily</button></> : null}</span></div>)}{!openItems.length ? <div><b>目前沒有保存的待處理項目。</b><span>按「建立掃描紀錄」後會保存 detected items。</span></div> : null}</div></article></section>
    <section className={styles.accountContentGrid}><article className={styles.accountContentCard}><div className={styles.accountContentHead}><div><span className="i20-kicker">Runs</span><h3>最近掃描紀錄</h3></div></div><div className={styles.accountPreferenceList}>{(payload?.runs || []).map((run: any) => <div key={run.id}><b>{run.run_type}｜{run.status}｜{run.detected_items} issues</b><span>Supabase {run.scanned_supabase_rooms}｜Daily {run.scanned_daily_rooms}｜{formatDateTime(run.created_at)}</span></div>)}</div></article><article className={styles.accountContentCard}><div className={styles.accountContentHead}><div><span className="i20-kicker">Policy</span><h3>處理原則</h3></div></div><div className={styles.accountPreferenceList}><div><b>active_overdue</b><span>優先結束 Supabase room；若 Daily 仍存在再刪 Daily。</span></div><div><b>active_daily_missing</b><span>使用者可能無法通話，優先結束或重新建立房間，不要讓前台顯示假可用。</span></div><div><b>orphan_daily_room</b><span>Daily 端有房但 Supabase 沒 active 對應，通常應刪 Daily。</span></div><div><b>active_without_members</b><span>建立或 join 流程中斷，通常應結束房間並查 reliability events。</span></div></div></article></section>
  </FormalOpsShell>;
}
