"use client";
import { useEffect, useMemo, useState } from "react";
import { FormalOpsShell, adminOpsNav } from "@/components/formalOps/FormalOpsShell";
import { formatDateTime, useAuthedJson } from "@/components/formalOps/useAuthedJson";
import styles from "@/components/image20/Image20Auxiliary.module.css";
const roleOptions = ["owner", "ops", "support", "safety", "finance", "viewer", "custom"] as const;
type Assignment = { id: string; user_id: string; role_key: string; permissions: string[]; status: string; note?: string | null; granted_at?: string | null; updated_at?: string | null };
export default function AdminRolesPage() {
  const { accessToken, authedFetch } = useAuthedJson("/admin/roles");
  const [assignments, setAssignments] = useState<Assignment[]>([]); const [presets, setPresets] = useState<any[]>([]); const [allPermissions, setAllPermissions] = useState<string[]>([]); const [currentAdmin, setCurrentAdmin] = useState<any>(null); const [message, setMessage] = useState("正在讀取管理權限…");
  const [form, setForm] = useState({ user_id: "", email: "", role_key: "viewer", permissions: "", status: "active", note: "" });
  const activeOwners = useMemo(() => assignments.filter((item) => item.status === "active" && item.role_key === "owner"), [assignments]);
  async function load() { const payload = await authedFetch("/api/admin/roles"); setAssignments(payload.assignments || []); setPresets(payload.presets || []); setAllPermissions(payload.all_permissions || []); setCurrentAdmin(payload.current_admin || null); }
  useEffect(() => { if (!accessToken) return; load().then(() => setMessage("")).catch((error) => setMessage(error.message)); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [accessToken]);
  async function createAssignment(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage("正在建立 admin role assignment…"); try { await authedFetch("/api/admin/roles", { method: "POST", body: JSON.stringify({ user_id: form.user_id || undefined, email: form.email || undefined, role_key: form.role_key, permissions: form.permissions.split(",").map((item) => item.trim()).filter(Boolean), status: form.status, note: form.note }) }); setForm({ user_id: "", email: "", role_key: "viewer", permissions: "", status: "active", note: "" }); await load(); setMessage("已建立管理權限。"); } catch (error: any) { setMessage(error?.message || "建立管理權限失敗。"); } }
  async function updateAssignment(id: string, patch: Record<string, unknown>) { setMessage("正在更新管理權限…"); try { await authedFetch(`/api/admin/roles/${id}`, { method: "PATCH", body: JSON.stringify(patch) }); await load(); setMessage("已更新管理權限。"); } catch (error: any) { setMessage(error?.message || "更新管理權限失敗。"); } }
  return (
    <FormalOpsShell activeHref="/admin/roles" navItems={adminOpsNav} eyebrow="Admin RBAC" title="權限管理" description="正式商業平台不能長期只靠 Vercel env 隱藏 Admin 入口；這裡建立 DB-backed role assignments，並保留 env 作為短期 break-glass fallback。" quoteTitle={currentAdmin ? `${currentAdmin.role_key} / ${currentAdmin.source}` : "讀取中"} quoteBody={`Active owners: ${activeOwners.length}。每次權限異動都會寫 admin_audit_logs。`} dataPage="admin-rbac-v115">
      {message ? <div className={styles.accountLoading}>{message}</div> : null}
      <section className={styles.accountMetricGrid}>
        <article className={styles.accountMetricCard}><span className="i20-kicker">Current Admin</span><h3>目前權限來源</h3><b>{currentAdmin?.role_key || "—"}</b><p>{currentAdmin?.source || "—"}｜{currentAdmin?.email || currentAdmin?.user_id || "—"}</p></article>
        <article className={styles.accountMetricCard}><span className="i20-kicker">Assignments</span><h3>權限指派</h3><b>{assignments.length}</b><p>active {assignments.filter((item) => item.status === "active").length} 筆</p></article>
        <article className={styles.accountMetricCard}><span className="i20-kicker">Owners</span><h3>Active Owner</h3><b>{activeOwners.length}</b><p>正式移除 env fallback 前，至少應有 1 位 active owner。</p></article>
      </section>
      <section className={styles.accountContentGrid}>
        <article className={styles.accountContentCard}><div className={styles.accountContentHead}><div><span className="i20-kicker">Create</span><h3>新增管理員權限</h3></div></div><form className={styles.formStack} onSubmit={createAssignment}><label><span className="i20-kicker">User ID</span><input value={form.user_id} onChange={(event) => setForm({ ...form, user_id: event.target.value })} placeholder="Supabase auth.users.id" /></label><label><span className="i20-kicker">或 Email</span><input value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="admin@example.com" /></label><label><span className="i20-kicker">Role</span><select value={form.role_key} onChange={(event) => setForm({ ...form, role_key: event.target.value })}>{roleOptions.map((role) => <option key={role} value={role}>{role}</option>)}</select></label><label><span className="i20-kicker">Custom Permissions</span><input value={form.permissions} onChange={(event) => setForm({ ...form, permissions: event.target.value })} placeholder="admin.read,users.read" /></label><label><span className="i20-kicker">Note</span><textarea rows={4} value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} /></label><button className="i20-btn peach" type="submit">建立權限</button></form></article>
        <article className={styles.accountContentCard}><div className={styles.accountContentHead}><div><span className="i20-kicker">Presets</span><h3>角色預設權限</h3></div></div><div className={styles.accountPreferenceList}>{presets.map((preset) => <div key={preset.role_key}><b>{preset.display_name}｜{preset.role_key}</b><span>{preset.description}</span><span>{(preset.permissions || []).join(", ")}</span></div>)}{!presets.length ? <div><b>尚未讀到 presets。</b><span>請先套用 v115 SQL migration。</span></div> : null}</div></article>
      </section>
      <section className={styles.accountContentGrid}>
        <article className={styles.accountContentCard}><div className={styles.accountContentHead}><div><span className="i20-kicker">Assignments</span><h3>目前權限指派</h3></div><button type="button" onClick={() => load().catch((error) => setMessage(error.message))}>重新整理</button></div><div className={styles.accountPreferenceList}>{assignments.map((assignment) => <div key={assignment.id}><b>{assignment.role_key}｜{assignment.status}</b><span>{assignment.user_id}｜{formatDateTime(assignment.granted_at || assignment.updated_at)}</span><span>{(assignment.permissions || []).length ? assignment.permissions.join(", ") : "使用角色預設權限"}</span><span>{assignment.status !== "active" ? <button type="button" onClick={() => updateAssignment(assignment.id, { status: "active" })}>啟用</button> : null} {assignment.status === "active" ? <button type="button" onClick={() => updateAssignment(assignment.id, { status: "inactive" })}>停用</button> : null} {assignment.status !== "revoked" ? <button type="button" onClick={() => updateAssignment(assignment.id, { status: "revoked" })}>撤銷</button> : null}</span></div>)}{!assignments.length ? <div><b>目前沒有 DB-backed 管理員。</b><span>你現在可能還是靠 ADMIN_EMAILS / ADMIN_USER_IDS 進入。請先建立至少一位 owner。</span></div> : null}</div></article>
        <article className={styles.accountContentCard}><div className={styles.accountContentHead}><div><span className="i20-kicker">Permissions</span><h3>可用權限字串</h3></div></div><div className={styles.accountPreferenceList}>{allPermissions.map((permission) => <div key={permission}><b>{permission}</b><span>可用於 custom role 或 route-level permission gate。</span></div>)}</div></article>
      </section>
    </FormalOpsShell>
  );
}
